export const permitted = '{type,slug,isActivated,token,userName,apiKey,webhook,'
  + 'clientId,clientSecret,botuser,password,phoneNumber,serviceId,consumerKey,'
  + 'consumerSecret,accessToken,accessTokenSecret,envName,clientAppId,accentColor,'
  + 'complementaryColor,botMessageColor,botMessageBackgroundColor,'
  + 'backgroundColor,headerLogo,headerTitle,botPicture,userPicture,'
  + 'onboardingMessage,userInputPlaceholder,expanderLogo,'
  + 'expanderTitle,conversationTimeToLive,characterLimit,'
  + 'characterLimit,openingType,welcomeMessage,refreshToken,'
  + 'oAuthCode,invocationName,webchatLocale}'

export const permittedUpdate = '{slug,isActivated,token,userName,apiKey,webhook,'
  + 'clientId,clientSecret,botuser,password,phoneNumber,serviceId,consumerKey,'
  + 'consumerSecret,accessToken,accessTokenSecret,clientAppId,accentColor,'
  + 'complementaryColor,botMessageColor,botMessageBackgroundColor,'
  + 'backgroundColor,headerLogo,headerTitle,botPicture,userPicture,'
  + 'onboardingMessage,userInputPlaceholder,expanderLogo,expanderTitle,'
  + 'conversationTimeToLive,characterLimit,'
  + 'openingType,welcomeMessage,refreshToken,'
  + 'invocationName,botEnvironmentId,webchatLocale}'
